/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ClinicalRegulatoryRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ResearchAndDevelopment.ClinicalRegulatoryOrganisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class ClinicalRegulatoryMainWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClinicalRegulatoryMainWorkAreaJPanel
     */
     private  JPanel userprocesscontainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private ClinicalRegulatoryOrganisation organization;
    public ClinicalRegulatoryMainWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount,Organization organization,Enterprise enterprise) {
        initComponents();
        this.userprocesscontainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization =  (ClinicalRegulatoryOrganisation)organization;
        this.enterprise = enterprise;
        valueLabel.setText(enterprise.getName());
        organisationjLabel.setText(organization.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        refreshTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        organisationjLabel = new javax.swing.JLabel();
        logoutjButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        regulatorySpecialistLeftjPanel = new javax.swing.JPanel();
        phaseIIjButton = new javax.swing.JButton();
        phaseIjButton = new javax.swing.JButton();
        phaseIIIjButton = new javax.swing.JButton();
        regulatorySpecialistRightjPanel = new javax.swing.JPanel();
        logoutjButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        enterpriseLabel.setText("Enterprise ");

        valueLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        valueLabel.setText("<value>");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("Organisation");

        organisationjLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        organisationjLabel.setText("Org Name");

        logoutjButton.setText("Logout");
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });

        jSplitPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setDividerSize(1);

        regulatorySpecialistLeftjPanel.setBackground(new java.awt.Color(153, 153, 153));

        phaseIIjButton.setText("Phase II");
        phaseIIjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phaseIIjButtonActionPerformed(evt);
            }
        });

        phaseIjButton.setText("Phase I ");
        phaseIjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phaseIjButtonActionPerformed(evt);
            }
        });

        phaseIIIjButton.setText("Phase III");
        phaseIIIjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phaseIIIjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regulatorySpecialistLeftjPanelLayout = new javax.swing.GroupLayout(regulatorySpecialistLeftjPanel);
        regulatorySpecialistLeftjPanel.setLayout(regulatorySpecialistLeftjPanelLayout);
        regulatorySpecialistLeftjPanelLayout.setHorizontalGroup(
            regulatorySpecialistLeftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regulatorySpecialistLeftjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(regulatorySpecialistLeftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(phaseIjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phaseIIjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phaseIIIjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        regulatorySpecialistLeftjPanelLayout.setVerticalGroup(
            regulatorySpecialistLeftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regulatorySpecialistLeftjPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(phaseIjButton)
                .addGap(42, 42, 42)
                .addComponent(phaseIIjButton)
                .addGap(34, 34, 34)
                .addComponent(phaseIIIjButton)
                .addContainerGap(514, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(regulatorySpecialistLeftjPanel);

        regulatorySpecialistRightjPanel.setBackground(new java.awt.Color(153, 153, 153));
        regulatorySpecialistRightjPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(regulatorySpecialistRightjPanel);

        logoutjButton1.setText("Logout");
        logoutjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1435, 1435, 1435)
                        .addComponent(refreshTestJButton)
                        .addGap(30, 30, 30)
                        .addComponent(logoutjButton)
                        .addGap(61, 61, 61))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(organisationjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(537, 537, 537))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1835, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshTestJButton)
                    .addComponent(logoutjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(organisationjLabel)
                    .addComponent(logoutjButton1))
                .addGap(44, 44, 44)
                .addComponent(jSplitPane1))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2284, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2284, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        // populateRequestTable();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        // TODO add your handling code here:
        userprocesscontainer.remove(this);
        Component[] componentArray = userprocesscontainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }//GEN-LAST:event_logoutjButtonActionPerformed

    private void phaseIIjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phaseIIjButtonActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) regulatorySpecialistRightjPanel.getLayout();
        regulatorySpecialistRightjPanel.add("drugScientistRightjPanel", new PhaseIIWorkDetailCRJPanel(regulatorySpecialistRightjPanel,organization,userAccount,enterprise));
        layout.next(regulatorySpecialistRightjPanel);
    }//GEN-LAST:event_phaseIIjButtonActionPerformed

    private void phaseIjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phaseIjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) regulatorySpecialistRightjPanel.getLayout();
        regulatorySpecialistRightjPanel.add("drugScientistRightjPanel", new PhaseIWorkDetailCRJPanel(regulatorySpecialistRightjPanel,organization,userAccount,enterprise));
        layout.next(regulatorySpecialistRightjPanel);       
    }//GEN-LAST:event_phaseIjButtonActionPerformed

    private void phaseIIIjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phaseIIIjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) regulatorySpecialistRightjPanel.getLayout();
        regulatorySpecialistRightjPanel.add("drugScientistRightjPanel", new PhaseIIIWorkDetailCRJPanel(regulatorySpecialistRightjPanel,organization,userAccount,enterprise));
        layout.next(regulatorySpecialistRightjPanel);
    }//GEN-LAST:event_phaseIIIjButtonActionPerformed

    private void logoutjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButton1ActionPerformed
        // TODO add your handling code here:
        userprocesscontainer.remove(this);
        Component[] componentArray = userprocesscontainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);
    }//GEN-LAST:event_logoutjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutjButton;
    private javax.swing.JButton logoutjButton1;
    private javax.swing.JLabel organisationjLabel;
    private javax.swing.JButton phaseIIIjButton;
    private javax.swing.JButton phaseIIjButton;
    private javax.swing.JButton phaseIjButton;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JPanel regulatorySpecialistLeftjPanel;
    private javax.swing.JPanel regulatorySpecialistRightjPanel;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
