/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ClinicalRegulatoryRole;

import Business.Organization.ResearchAndDevelopment.ClinicalRegulatoryOrganisation;
import Business.Organization.ResearchAndDevelopment.ClinicalTrialsOrganisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ClinicalDrugPhaseOneTestWorkRequest;
import Business.WorkQueue.TiterTest;
import java.awt.BasicStroke;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Stroke;
import static java.lang.Math.random;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.axis.TickUnitSource;
import org.jfree.chart.labels.StandardXYItemLabelGenerator;
import org.jfree.chart.labels.XYItemLabelGenerator;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.DefaultXYDataset;
import org.jfree.data.xy.XYDataset;

/**
 *
 * @author Lenovo
 */
public class PhaseTestDetailCRJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PhaseTestDetailJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private ClinicalRegulatoryOrganisation organization;
    private ClinicalDrugPhaseOneTestWorkRequest cdtwr;
    private static final Random random = new Random();
    public PhaseTestDetailCRJPanel(JPanel userProcessContainer, UserAccount userAccount ,ClinicalRegulatoryOrganisation organization, ClinicalDrugPhaseOneTestWorkRequest cdtwr) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.cdtwr = cdtwr;
        this.organization =organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        getResultjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        solubilityjTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        gastricjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        transitTimejTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        chemicalInstabilityjTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FlowratejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        serumProteinjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        molecularSizejTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        polarityjTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        formationjTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        dissolution = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        logPjTextField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        drugConcentrationjTextField1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        clearanceTimejTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        HalfLifejTextField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        passjRadioButton = new javax.swing.JRadioButton();
        failjRadioButton = new javax.swing.JRadioButton();
        submitjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Absorption");

        jLabel12.setText("Compound solubility");

        jLabel13.setText("Gastric emptying time");

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jLabel14.setText(" Intestinal transit time");

        jLabel15.setText(" Chemical instability");

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(153, 153, 153));

        getResultjButton.setText("Get Test result ");
        getResultjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getResultjButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Compound solubility");

        jLabel2.setText("Gastric emptying time");

        gastricjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastricjTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText(" Intestinal transit time");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Absorption");

        jLabel5.setText(" Chemical instability");

        chemicalInstabilityjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemicalInstabilityjTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Distribution");

        jLabel7.setText("Blood flow rate");

        jLabel8.setText("Serum Proteins");

        serumProteinjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serumProteinjTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText(" Molecular size μm ");

        jLabel10.setText("Polarity ");

        polarityjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polarityjTextFieldActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Metabolism");

        jLabel17.setText("Glucuronide formation");

        jLabel18.setText("Rate of dissolution");

        dissolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dissolutionActionPerformed(evt);
            }
        });

        jLabel19.setText(" cLogP ***value");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Elimination");

        jLabel22.setText("Drug Concentration");

        jLabel23.setText("Clearance Time");

        clearanceTimejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearanceTimejTextFieldActionPerformed(evt);
            }
        });

        jLabel24.setText("  Plasma half-life ");

        jLabel26.setText("***coefficient between n-octanol and water log(coctanol/cwater)");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Pharmacokinetics Analysis");

        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Result");

        passjRadioButton.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(passjRadioButton);
        passjRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passjRadioButton.setText("Pass");

        failjRadioButton.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(failjRadioButton);
        failjRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        failjRadioButton.setText("Fail");

        submitjButton.setText("Submit Result");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Get Detail Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(transitTimejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(chemicalInstabilityjTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(15, 15, 15)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(solubilityjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(gastricjTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(getResultjButton)
                                .addGap(124, 124, 124)
                                .addComponent(jLabel4)))
                        .addGap(204, 204, 204)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(55, 55, 55)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(molecularSizejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(polarityjTextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(FlowratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(serumProteinjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(3, 3, 3)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(571, 571, 571)
                        .addComponent(jLabel27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(backjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(69, 69, 69)
                                .addComponent(logPjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(formationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dissolution, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addComponent(jLabel21))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel23)
                                                    .addComponent(jLabel22))))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(HalfLifejTextField)
                                            .addComponent(drugConcentrationjTextField1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(clearanceTimejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel20)
                                .addGap(27, 27, 27)
                                .addComponent(passjRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(failjRadioButton)
                                .addGap(66, 66, 66)
                                .addComponent(submitjButton)))))
                .addGap(205, 205, 205))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel27)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jButton1))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(FlowratejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(serumProteinjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(molecularSizejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(polarityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(getResultjButton)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(solubilityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(gastricjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(transitTimejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(chemicalInstabilityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(formationjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(dissolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(logPjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(drugConcentrationjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(clearanceTimejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(HalfLifejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(failjRadioButton)
                        .addComponent(passjRadioButton)
                        .addComponent(submitjButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel26)
                        .addComponent(backjButton)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gastricjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastricjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gastricjTextFieldActionPerformed

    private void chemicalInstabilityjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemicalInstabilityjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chemicalInstabilityjTextFieldActionPerformed

    private void serumProteinjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serumProteinjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serumProteinjTextFieldActionPerformed

    private void polarityjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polarityjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_polarityjTextFieldActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void dissolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dissolutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dissolutionActionPerformed

    private void clearanceTimejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearanceTimejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearanceTimejTextFieldActionPerformed

    private void getResultjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getResultjButtonActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("#.##");
                    df.setRoundingMode(RoundingMode.CEILING);
          solubilityjTextField.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculatecompoundSolubility())));        
          populatecolour(solubilityjTextField,cdtwr.getCpd().getPharmacokinetics().calculatecompoundSolubility());
          
          gastricjTextField.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculateGastricEmptyingTime())));   
          populatecolour(gastricjTextField,cdtwr.getCpd().getPharmacokinetics().calculateGastricEmptyingTime());
          
          transitTimejTextField.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculateintestinalTransitTime())));       
          populatecolour(transitTimejTextField,cdtwr.getCpd().getPharmacokinetics().calculateintestinalTransitTime());
          
          chemicalInstabilityjTextField.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculatechemicalInstability())));       
          populatecolour(chemicalInstabilityjTextField,cdtwr.getCpd().getPharmacokinetics().calculatechemicalInstability());
          
          formationjTextField.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculateglucuronideFormation())));       
          populatecolour(formationjTextField,cdtwr.getCpd().getPharmacokinetics().calculateglucuronideFormation());
          
          dissolution.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculaterateOfDissolution())));       
          populatecolour(dissolution,cdtwr.getCpd().getPharmacokinetics().calculaterateOfDissolution());
          
          logPjTextField.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculatecLogPvalue())));       
          populatecolour(logPjTextField,cdtwr.getCpd().getPharmacokinetics().calculatecLogPvalue());
          
          FlowratejTextField.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculatebloodFlowRate())));       
          populatecolour(FlowratejTextField,cdtwr.getCpd().getPharmacokinetics().calculatebloodFlowRate());
          
          serumProteinjTextField.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculateserumProtein())));       
          populatecolour(serumProteinjTextField,cdtwr.getCpd().getPharmacokinetics().calculateserumProtein());
          
          molecularSizejTextField.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculatemolecularSize())));       
          populatecolour(molecularSizejTextField,cdtwr.getCpd().getPharmacokinetics().calculatemolecularSize());
          
          polarityjTextField.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculatepolarity())));       
          populatecolour(polarityjTextField,cdtwr.getCpd().getPharmacokinetics().calculatepolarity());
          
          drugConcentrationjTextField1.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculatedrugConcentration())));       
          populatecolour(drugConcentrationjTextField1,cdtwr.getCpd().getPharmacokinetics().calculatedrugConcentration());
          
           HalfLifejTextField.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculateplasmaHalfLife())));       
          populatecolour(HalfLifejTextField,cdtwr.getCpd().getPharmacokinetics().calculateplasmaHalfLife());
          
          clearanceTimejTextField.setText(String.valueOf(df.format(cdtwr.getCpd().getPharmacokinetics().calculateclearanceTime())));       
          populatecolour(clearanceTimejTextField,cdtwr.getCpd().getPharmacokinetics().calculateclearanceTime());
          
          
          cdtwr.setTestResult("Finished");
         
          
          
    }//GEN-LAST:event_getResultjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:

        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
                PhaseIWorkDetailCRJPanel dwjp = (PhaseIWorkDetailCRJPanel) component;
               dwjp.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed
        // TODO add your handling code here:
           if (passjRadioButton.isSelected())
        {  
            cdtwr.setStatus("Pass");
        }
        else
         { cdtwr.setStatus("Failed");}
         JOptionPane.showMessageDialog(null,"Test Result Added");        
    }//GEN-LAST:event_submitjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          final DefaultXYDataset dataset1 = new DefaultXYDataset();
        
            int y = cdtwr.getCpd().getPharmacokinetics().getNumberHealthyPeople()+ cdtwr.getCpd().getPharmacokinetics().getUnhealthyPeople() ;  //takes the number of people in the test 
        
        dataset1.addSeries("Compound solubility1 " , createSeries(y,Double.valueOf(solubilityjTextField.getText())));
        dataset1.addSeries("Gastric Emptying Time1 " , createSeries(y,Double.valueOf(gastricjTextField.getText())));
        dataset1.addSeries("Transit Time " , createSeries(y,Double.valueOf(transitTimejTextField.getText())));
        dataset1.addSeries("Instability Time " , createSeries(y,Double.valueOf(chemicalInstabilityjTextField.getText())));
        int x = 1;
        JFreeChart chart1 = createChart(dataset1,x);
        ChartFrame frame = new  ChartFrame("Bar Chart",chart1);
        frame.setVisible(true);
        frame.setSize(1000, 900);
        frame.setLocation(0, 0);
        frame.pack();
        //frame.setLocationRelativeTo(null);
        //frame.pack();
        //frame.setLocationRelativeTo(null);
        
        
        final DefaultXYDataset dataset2 = new DefaultXYDataset();
        
        dataset2.addSeries("Glucoronide Formation " , createSeries(y,Double.valueOf(formationjTextField.getText())));
        dataset2.addSeries("Rate of Dissolution" , createSeries(y,Double.valueOf(dissolution.getText())));
        dataset2.addSeries("CLog P Value " , createSeries(y,Double.valueOf(logPjTextField.getText())));
        x = 2;
        JFreeChart chart2 = createChart(dataset2,x);
        ChartFrame frame2 = new  ChartFrame("Bar Chart",chart2);
        frame2.setVisible(true);
        frame2.setSize(1000, 900);
        frame.setLocation(1000, 0);
        frame2.pack();
       //  frame2.setLocationRelativeTo(null);
       // frame2.pack();
       //  frame2.setLocationRelativeTo(null);
         
        final DefaultXYDataset dataset3 = new DefaultXYDataset();
        x = 3;
        dataset3.addSeries("Blood Flow Rate " , createSeries(y,Double.valueOf(FlowratejTextField.getText())));
        dataset3.addSeries("Serum Proteins" , createSeries(y,Double.valueOf(serumProteinjTextField.getText())));
        dataset3.addSeries(" Molecular size " , createSeries(y,Double.valueOf(molecularSizejTextField.getText())));
        dataset3.addSeries("Polarity " , createSeries(y,Double.valueOf(polarityjTextField.getText())));

        JFreeChart chart3 = createChart(dataset3,x);
        ChartFrame frame3 = new  ChartFrame("Bar Chart",chart3);
        frame3.setVisible(true);
        frame3.setSize(1000, 900);
        frame3.setLocation(1,500);
        frame3.pack();
        
         
         
         
         final DefaultXYDataset dataset4 = new DefaultXYDataset();
        
        dataset4.addSeries("Drug Concentration " , createSeries(y,Double.valueOf(formationjTextField.getText())));
        dataset4.addSeries("Clearance Time" , createSeries(y,Double.valueOf(dissolution.getText())));
        dataset4.addSeries("Plasma half-life" , createSeries(y,Double.valueOf(logPjTextField.getText())));
        x= 4;
        JFreeChart chart4 = createChart(dataset4,x);
        ChartFrame frame4 = new  ChartFrame("Bar Chart",chart4);
        frame4.setVisible(true);
        frame4.setSize(1000, 900);
        frame4.setLocation(1000,500);
        frame4.pack();
        

        
    }//GEN-LAST:event_jButton1ActionPerformed

public void populatecolour(Component component,double temp ){
     if( temp< .1 )
          {
              component.setBackground(Color.getHSBColor(0,192,208));  
          }
     else if(temp>.9)
             {
                 component.setBackground(Color.lightGray);
             }
     else {
          component.setBackground(Color.getHSBColor(0,186,142));
                  

     }
}

  private JFreeChart createChart(XYDataset dataset,int x) {

        // create the chart...
        String title = "";
        if(x==1){title = "Pharmacokinetics Result - Absorption";}
        if(x==2){title = "Pharmacokinetics Result - Metabolism";}
        if(x==3){title = "Pharmacokinetics Result - Distribution";}
        if(x==4){title = "Pharmacokinetics Result - Elimination";}
        
        
        
        
        
        JFreeChart chart = ChartFactory.createXYLineChart(
            title, // chart title
            "Total Number of People", // x axis label
            "Paramters Result ", // y axis label
            dataset,  // initial series
            PlotOrientation.VERTICAL, // orientation
            true, // include legend
            true, // tooltips?
            false // URLs?
            );

        // set chart background
        chart.setBackgroundPaint(Color.white);

        // set a few custom plot features
        XYPlot plot = (XYPlot) chart.getPlot();
       // plot.setBackgroundPaint(new Color(0xffffe0));
        plot.setDomainGridlinesVisible(true);
        plot.setDomainGridlinePaint(Color.lightGray);
        plot.setRangeGridlinePaint(Color.lightGray);

        // set the plot's axes to display integers
        TickUnitSource ticks = NumberAxis.createIntegerTickUnits();
        NumberAxis domain = (NumberAxis) plot.getDomainAxis();
        domain.setStandardTickUnits(ticks);
        NumberAxis range = (NumberAxis) plot.getRangeAxis();
        range.setStandardTickUnits(ticks);

        // render shapes and lines
        XYLineAndShapeRenderer renderer =
            new XYLineAndShapeRenderer(true, true);
        plot.setRenderer(renderer);
        renderer.setBaseShapesVisible(true);
        renderer.setBaseShapesFilled(true);

        // set the renderer's stroke
        Stroke stroke = new BasicStroke(
            3f, BasicStroke.CAP_ROUND, BasicStroke.JOIN_BEVEL);
        renderer.setBaseOutlineStroke(stroke);

 
        return chart;
    }
     
       private double[][] createSeries(int totalpeople,double cell) {
        double[][] series = new double[2][totalpeople];
        for (int i = 0; i < totalpeople; i++) {
            series[0][i] = (double) i;                    //X axis 
            series[1][i] = cell +random.nextGaussian();  // Y Axis
            
        }
        return series;
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FlowratejTextField;
    private javax.swing.JTextField HalfLifejTextField;
    private javax.swing.JButton backjButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField chemicalInstabilityjTextField;
    private javax.swing.JTextField clearanceTimejTextField;
    private javax.swing.JTextField dissolution;
    private javax.swing.JTextField drugConcentrationjTextField1;
    private javax.swing.JRadioButton failjRadioButton;
    private javax.swing.JTextField formationjTextField;
    private javax.swing.JTextField gastricjTextField;
    private javax.swing.JButton getResultjButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField logPjTextField;
    private javax.swing.JTextField molecularSizejTextField;
    private javax.swing.JRadioButton passjRadioButton;
    private javax.swing.JTextField polarityjTextField;
    private javax.swing.JTextField serumProteinjTextField;
    private javax.swing.JTextField solubilityjTextField;
    private javax.swing.JButton submitjButton;
    private javax.swing.JTextField transitTimejTextField;
    // End of variables declaration//GEN-END:variables
}
