/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
//import UserInterface.SystemAdminWorkArea.systemAdminJPanel;
import com.sun.glass.events.KeyEvent;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */

public class loginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form loginJPanel
     */
    
    JPanel downjPanel;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    protected JFrame MainJframe; 
    public loginJPanel(JPanel downjPanel) {
        initComponents();
        this.downjPanel = downjPanel;
         system = dB4OUtil.retrieveSystem();

       
        
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
 

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userNamejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        loginjButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, 28));

        userNamejTextField.setMinimumSize(new java.awt.Dimension(100, 26));
        userNamejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNamejTextFieldKeyPressed(evt);
            }
        });
        jPanel1.add(userNamejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, 28));

        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyReleased(evt);
            }
        });
        jPanel1.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, 150, -1));

        loginjButton.setText("Login");
        loginjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 150, -1));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1451, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButtonActionPerformed
        // TODO add your handling code here:
//        String userName = userNamejTextField.getText();
//        // Get Password
//        char[] passwordCharArray = jPasswordField.getPassword();
//        String password = String.valueOf(passwordCharArray);
//        String sysadmin = "sysadmin";
//        if(userName.equals(sysadmin) && password.equals(sysadmin)){
//            JOptionPane.showMessageDialog(null,"Welcome Sysadmin!");
//            userNamejTextField.setText("");
//            jPasswordField.setText("");
//           systemAdminJPanel sap = new systemAdminJPanel(downjPanel);
//           downjPanel.add("sap", sap);
//           CardLayout layout = (CardLayout) downjPanel.getLayout();
//           layout.next(downjPanel);
//        }
//        else{
//            JOptionPane.showMessageDialog(null,"something is wrong");
//        }
  String userName = userNamejTextField.getText();
        // Get Password
        char[] passwordCharArray = jPasswordField.getPassword();
        String password = String.valueOf(passwordCharArray);
        
        UserAccount userAccount = null;
        //check in the system user Account category 
        
        userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        Enterprise inEnterprise = null;
        Organization inOrganization = null;
        if(userAccount == null){    
            //go inside each network to check each enterprise 
            for(Network network: system.getNetworkList()){
                //chcek again each enterprise 
                for(Enterprise enterprise: network.getEnterpriseDirectory().getEl()){
                    userAccount = enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    if(userAccount == null){
                        //chcek again each organiation 
                        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                            userAccount = organization.getUserAccountDirectory().authenticateUser(userName, password);
                            if(userAccount != null){
                                inEnterprise = enterprise;
                                inOrganization = organization;
                                break;
                            }
                        }
                    }
                    else{
                        inEnterprise = enterprise;
                        break;          
                    }
                    if(inOrganization != null){
                        break;
                    }
                }
                if(inEnterprise != null){
                    break;
                
            }
           }
        }
        if(userAccount == null ){
            JOptionPane.showMessageDialog(null,"Invalid Credentials!");
            return;
        }
        else{
            CardLayout  layout = (CardLayout) downjPanel.getLayout();
            downjPanel.add("WorkArea",userAccount.getRole().createWorkArea(downjPanel,userAccount,inOrganization,inEnterprise,system ));
            layout.next(downjPanel);
        }
        
        

      //   loginJButton.setEnabled(false);
        
          userNamejTextField.setText("");
            jPasswordField.setText("");
    }//GEN-LAST:event_loginjButtonActionPerformed

    private void userNamejTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNamejTextFieldKeyPressed
        // TODO add your handling code here:
        int keyp = evt.getKeyCode();
        if ((keyp >= evt.VK_A && keyp<=evt.VK_Z)||(keyp==KeyEvent.VK_BACKSPACE)|| (keyp >= evt.VK_0 && keyp<=evt.VK_9||keyp ==evt.VK_CAPS_LOCK))
        {
             
            userNamejTextField.setEditable(true);
            userNamejTextField.setBackground(Color.YELLOW);
            
        }
        else
        {
            userNamejTextField.setEditable(false);
            userNamejTextField.setBackground(Color.red);
            getToolkit().beep();
            JOptionPane.showMessageDialog(null,"Special Characters Prohibited  as username");
            userNamejTextField.setBackground(Color.WHITE);
            userNamejTextField.requestFocusInWindow();
        }
        
        
        
        
    }//GEN-LAST:event_userNamejTextFieldKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyPressed
        // TODO add your handling code here:
        jPasswordField.setEditable(true);
        jPasswordField.setBackground(Color.YELLOW);
        int keyp = evt.getKeyCode();
         if (keyp==KeyEvent.VK_BACKSPACE){
             jPasswordField.setBackground(Color.LIGHT_GRAY);
         }
        
        
        
    }//GEN-LAST:event_jPasswordFieldKeyPressed

    private void jPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyReleased
        // TODO add your handling code here:
        jPasswordField.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_jPasswordFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JButton loginjButton;
    private javax.swing.JTextField userNamejTextField;
    // End of variables declaration//GEN-END:variables
}
