package userinterface.SystemAdminWorkArea;


import Business.DB4OUtil.DB4OUtil;
import javax.swing.JPanel;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem  system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    
    
    
    
    
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem  system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateTree();
    }
    
    
    
    public void populateTree(){
        DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
        ArrayList<Network> networkList = system.getNetworkList();
        ArrayList<Enterprise> enterpriseList;
        ArrayList<Organization>organizationList;
        
        Network network;
        Enterprise enterprise;
        Organization organization;
        
        DefaultMutableTreeNode networks = new DefaultMutableTreeNode("Networks");
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        
        root.removeAllChildren();
        root.insert(networks,0);
        
        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;
        
        for(int i = 0; i < networkList.size();i++){
            network = networkList.get(i);
            networkNode =  new DefaultMutableTreeNode(network.getName());
           networks.insert(networkNode,i);
            
            enterpriseList = network.getEnterpriseDirectory().getEl();
            for(int j = 0; j <enterpriseList.size();j++){
                enterprise = enterpriseList.get(j);
                enterpriseNode =  new DefaultMutableTreeNode(enterprise.getName());
                networkNode.insert(enterpriseNode,j);
                
                organizationList=enterprise.getOrganizationDirectory().getOrganizationList();
                for(int k = 0;k <organizationList.size();k++){
                    organization = organizationList.get(j);
                    organizationNode =  new DefaultMutableTreeNode(enterprise.getName());
                    enterpriseNode.insert(organizationNode,k);   
                } 
            }
        }
        model.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        selectedNodeJLabel = new javax.swing.JLabel();
        MnageEnterprisejButton = new javax.swing.JButton();
        manageNetworkjButton = new javax.swing.JButton();
        MnageEnterpriseAdminjButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        logoutjButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(203, 95, 74));
        jLabel1.setText("Selected Node  ");

        selectedNodeJLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        selectedNodeJLabel.setForeground(new java.awt.Color(203, 95, 74));
        selectedNodeJLabel.setText("View Selected Node");

        MnageEnterprisejButton.setText("Manage Enterprise");
        MnageEnterprisejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnageEnterprisejButtonActionPerformed(evt);
            }
        });

        manageNetworkjButton.setText("Manage Network");
        manageNetworkjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNetworkjButtonActionPerformed(evt);
            }
        });

        MnageEnterpriseAdminjButton1.setText("Manage Enterprise Admin");
        MnageEnterpriseAdminjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnageEnterpriseAdminjButton1ActionPerformed(evt);
            }
        });

        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        logoutjButton.setText("Logout");
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)
                        .addGap(237, 237, 237)
                        .addComponent(selectedNodeJLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MnageEnterprisejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageNetworkjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MnageEnterpriseAdminjButton1))))
                .addContainerGap(416, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutjButton)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutjButton)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(selectedNodeJLabel))
                        .addGap(68, 68, 68)
                        .addComponent(manageNetworkjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MnageEnterprisejButton)
                        .addGap(29, 29, 29)))
                .addGap(16, 16, 16)
                .addComponent(MnageEnterpriseAdminjButton1)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void manageNetworkjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNetworkjButtonActionPerformed
        // TODO add your handling code here:
        ManageNetworkJPanel  manageNetworkJPanel = new ManageNetworkJPanel(userProcessContainer,system);
        userProcessContainer.add("manageN",manageNetworkJPanel);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
      
      
        
    }//GEN-LAST:event_manageNetworkjButtonActionPerformed

    private void MnageEnterprisejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnageEnterprisejButtonActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseJPanel  manageEnterpriseJPanel = new ManageEnterpriseJPanel(userProcessContainer,system);
        userProcessContainer.add("manageE",manageEnterpriseJPanel);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_MnageEnterprisejButtonActionPerformed

    private void MnageEnterpriseAdminjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnageEnterpriseAdminjButton1ActionPerformed
        // TODO add your handling code here:
        
         ManageEnterpriseAdminJPanel  manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(userProcessContainer,system);
         userProcessContainer.add("manageEa",manageEnterpriseAdminJPanel);
         CardLayout layout= (CardLayout)userProcessContainer.getLayout();
         layout.next(userProcessContainer);
    }//GEN-LAST:event_MnageEnterpriseAdminjButton1ActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        // TODO add your handling code here:
        
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        if(selectedNode!=null){
            selectedNodeJLabel.setText(selectedNode.toString());
            
        }
            
        
        
        
        
    }//GEN-LAST:event_jTree1ValueChanged

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
         dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MnageEnterpriseAdminjButton1;
    private javax.swing.JButton MnageEnterprisejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton logoutjButton;
    private javax.swing.JButton manageNetworkjButton;
    private javax.swing.JLabel selectedNodeJLabel;
    // End of variables declaration//GEN-END:variables
}
