/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ClinicalTrialResearchRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ResearchAndDevelopment.ClinicalTrialsOrganisation;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class ClinicalTrialReasearchAssociateWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClinicalTestingWorkAreaJPanel
     */
     private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private ClinicalTrialsOrganisation clinicalTrialOrganization;
    private Enterprise enterprise;
    public ClinicalTrialReasearchAssociateWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, EcoSystem business,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.enterprise = enterprise;
        this.clinicalTrialOrganization = (ClinicalTrialsOrganisation)organization;
        valueLabel.setText(enterprise.getName());
        organisationjLabel.setText(organization.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        organisationjLabel = new javax.swing.JLabel();
        logoutjButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        drugScientistLeftjPanel = new javax.swing.JPanel();
        preClinicaljButton = new javax.swing.JButton();
        discoverjButton = new javax.swing.JButton();
        clinicalResearchjButton = new javax.swing.JButton();
        clinicalTestRightjPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        enterpriseLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        enterpriseLabel.setText("Enterprise ");

        valueLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        valueLabel.setText("<value>");

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Organisation");

        organisationjLabel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        organisationjLabel.setText("Org Name");

        logoutjButton.setText("Logout");
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });

        jSplitPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setDividerSize(1);

        drugScientistLeftjPanel.setBackground(new java.awt.Color(153, 153, 153));

        preClinicaljButton.setText("Pre-Clinical Trials");
        preClinicaljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preClinicaljButtonActionPerformed(evt);
            }
        });

        discoverjButton.setText("New Drug  Development Trials");
        discoverjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discoverjButtonActionPerformed(evt);
            }
        });

        clinicalResearchjButton.setText("Clinical Research");
        clinicalResearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clinicalResearchjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drugScientistLeftjPanelLayout = new javax.swing.GroupLayout(drugScientistLeftjPanel);
        drugScientistLeftjPanel.setLayout(drugScientistLeftjPanelLayout);
        drugScientistLeftjPanelLayout.setHorizontalGroup(
            drugScientistLeftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugScientistLeftjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(drugScientistLeftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(discoverjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(preClinicaljButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clinicalResearchjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        drugScientistLeftjPanelLayout.setVerticalGroup(
            drugScientistLeftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugScientistLeftjPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(discoverjButton)
                .addGap(39, 39, 39)
                .addComponent(preClinicaljButton)
                .addGap(40, 40, 40)
                .addComponent(clinicalResearchjButton)
                .addGap(337, 337, 337))
        );

        jSplitPane1.setLeftComponent(drugScientistLeftjPanel);

        clinicalTestRightjPanel.setBackground(new java.awt.Color(153, 153, 153));
        clinicalTestRightjPanel.setPreferredSize(new java.awt.Dimension(252, 522));
        clinicalTestRightjPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(clinicalTestRightjPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(organisationjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(349, 349, 349))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 2003, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutjButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(organisationjLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 807, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logoutjButtonActionPerformed

    private void preClinicaljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preClinicaljButtonActionPerformed
        // TODO add your handling code here:

        CardLayout layout = (CardLayout) clinicalTestRightjPanel.getLayout();
        clinicalTestRightjPanel.add("PreClinicalWorkAreaJPanel", new PreClinicalTestWorkAreaCTJPanel(clinicalTestRightjPanel,userAccount,clinicalTrialOrganization));
        layout.next(clinicalTestRightjPanel);

    }//GEN-LAST:event_preClinicaljButtonActionPerformed

    private void discoverjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discoverjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) clinicalTestRightjPanel.getLayout();
        clinicalTestRightjPanel.add("ClinicalTrailResearchWorkAreaJPanel", new ClinicalTrailResearchWorkAreaJPanel(clinicalTestRightjPanel,userAccount,clinicalTrialOrganization));
        layout.next(clinicalTestRightjPanel);
    }//GEN-LAST:event_discoverjButtonActionPerformed

    private void clinicalResearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clinicalResearchjButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Coming Soon .. Work in Progress ! ");
        
        
        
    }//GEN-LAST:event_clinicalResearchjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clinicalResearchjButton;
    private javax.swing.JPanel clinicalTestRightjPanel;
    private javax.swing.JButton discoverjButton;
    private javax.swing.JPanel drugScientistLeftjPanel;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutjButton;
    private javax.swing.JLabel organisationjLabel;
    private javax.swing.JButton preClinicaljButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
