/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ClinicalTrialResearchRole;

import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.PriclinicalWorkRequest;
import Business.WorkQueue.TiterTest;
import Business.WorkQueue.WorkQueue;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class ProcessInVitroTestCTJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessInVitroTestCTJPanel
     */
 JPanel userProcessContainer;
 PriclinicalWorkRequest pwr;
 private Timer timer = null;
 private int count = 0;
  int y = 20 ;

    ProcessInVitroTestCTJPanel(JPanel userProcessContainer,PriclinicalWorkRequest pwr ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pwr = pwr;
        experimentTimejTextField.setText(String.valueOf(pwr.getExperimentTime()));
        temparaturejTextField.setText(String.valueOf(pwr.getTemperature()));
        
        populateComboBox();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        startjButton = new javax.swing.JButton();
        jProgressBar = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        titerSetupjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        rosjTextField = new javax.swing.JTextField();
        cellViajTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addReportjButton = new javax.swing.JButton();
        titerjComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        experimentTimejTextField = new javax.swing.JTextField();
        temparaturejTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passjRadioButton = new javax.swing.JRadioButton();
        failjRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));

        startjButton.setText("Start");
        startjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startjButtonActionPerformed(evt);
            }
        });

        jProgressBar.setStringPainted(true);

        titerSetupjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titer Plate No", "Total Assay ", "Dose Level", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(titerSetupjTable);

        jLabel1.setText("ROS");

        rosjTextField.setEnabled(false);

        cellViajTextField.setEnabled(false);

        jLabel2.setText("Cell Viability");

        addReportjButton.setText("Add Report");
        addReportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReportjButtonActionPerformed(evt);
            }
        });

        titerjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titerjComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Incubate temperature ");

        jLabel5.setText("Experiment Time (Min)");

        experimentTimejTextField.setEnabled(false);

        temparaturejTextField.setEnabled(false);

        jLabel16.setText("°C");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Result");

        passjRadioButton.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(passjRadioButton);
        passjRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        passjRadioButton.setText("Pass");

        failjRadioButton.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(failjRadioButton);
        failjRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        failjRadioButton.setText("Fail");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Titer Plate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titerjComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 134, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(880, 880, 880)
                                .addComponent(addReportjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(276, 276, 276)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cellViajTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                                .addComponent(rosjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(passjRadioButton)
                                                .addGap(18, 18, 18)
                                                .addComponent(failjRadioButton))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(startjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(experimentTimejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(temparaturejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titerjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(experimentTimejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel3)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(temparaturejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startjButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rosjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cellViajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(failjRadioButton)
                            .addComponent(passjRadioButton))
                        .addGap(18, 18, 18)
                        .addComponent(addReportjButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(235, 235, 235))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void titerjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titerjComboBoxActionPerformed
        // TODO add your handling code here:
        
        TiterTest tt = (TiterTest)titerjComboBox.getSelectedItem();
        
        
        for(TiterTest titer:pwr.getTiterPlate()){
            if(titer.equals(tt)){
                populateTiterTable(titer);
            }
        }
         jProgressBar.setValue(0);
 
        
    }//GEN-LAST:event_titerjComboBoxActionPerformed

    private void startjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startjButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = titerSetupjTable.getSelectedRow();
          if (selectedRow >= 0) {
                   jProgressBar.setValue(0);
                 Thread progressBar = new Thread() {
            public void run() {
                for (int t = 0 ;t < 5;t++ ) {
                   
                    try {
                         
                         jProgressBar.setValue(y);
                        sleep(100);
                       populate();
                         System.out.println("Value of Progress Bar "+jProgressBar.getValue());

                    } catch (Exception e) {
                        JOptionPane.showConfirmDialog(null, "Progress Bar error");
                    }

                }
                JOptionPane.showMessageDialog(null,"Test Completed");
                populatey();
                
                
                   TiterTest tt = (TiterTest) titerSetupjTable.getValueAt(selectedRow, 0);
                   tt.setTiterTest("Done");
                   Random r = new Random();
                   Double sample = r.nextDouble() * 100;
                   tt.setCellViability((sample));
                   tt.setRos(sample*.8);
                   
                   
                    DecimalFormat df = new DecimalFormat("#.##");
                    df.setRoundingMode(RoundingMode.CEILING);
                   
                   rosjTextField.setText(String.valueOf(df.format(sample)));
                   cellViajTextField.setText(String.valueOf(df.format(sample*0.8)));
                           
                
                
   
            }
                 };
                 progressBar.start();
          }
          else
                {
                   JOptionPane.showMessageDialog(null,"Please Select the titer Plate Number from the Table ");
                }
        
    }//GEN-LAST:event_startjButtonActionPerformed

    
    public void populate(){
        this.y = y + 20;
    }
    public void populatey(){
        this.y = 20;
    }
    private void addReportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReportjButtonActionPerformed
        // TODO add your handling code here:
        
        if(passjRadioButton.isSelected()||failjRadioButton.isSelected()){
        
        pwr.setStatus("Done");
        
         if (passjRadioButton.isSelected())
        {
             pwr.setPreClinicalTestResult("Pass");
        }
        else
         { pwr.setPreClinicalTestResult("Failed");}
         
         pwr.setStatus("Resolved");
         
         JOptionPane.showMessageDialog(null,"Test Result Added");
          rosjTextField.setText("");
          cellViajTextField.setText("");
          passjRadioButton.setSelected(false);
          failjRadioButton.setSelected(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"Please Select the Status of Test");
        }
         
        
     
    }//GEN-LAST:event_addReportjButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        InVitroTestProcessWorkAreaJPanelCT dwjp = (InVitroTestProcessWorkAreaJPanelCT) component;
        dwjp.populateTableRequest();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addReportjButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cellViajTextField;
    private javax.swing.JTextField experimentTimejTextField;
    private javax.swing.JRadioButton failjRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton passjRadioButton;
    private javax.swing.JTextField rosjTextField;
    private javax.swing.JButton startjButton;
    private javax.swing.JTextField temparaturejTextField;
    private javax.swing.JTable titerSetupjTable;
    private javax.swing.JComboBox titerjComboBox;
    // End of variables declaration//GEN-END:variables

    private void populateComboBox() {
       for(TiterTest tt:pwr.getTiterPlate()){         
           titerjComboBox.addItem(tt);
       }
    }

    private void populateTiterTable(TiterTest titer) {
        DefaultTableModel model = (DefaultTableModel) titerSetupjTable.getModel();

        model.setRowCount(0);  
        Object[] row = new Object[4];
        row[0] = titer;
        row[1] = titer.getMediumQuantity();
        row[2] = titer.getTotalNumberofAssay();
        row[3] = titer.getTiterTest() == null ? "Pending" : titer.getTiterTest();
        model.addRow(row);   
    }
}
