/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ClinicalTrialResearchRole;

import Business.Organization.ResearchAndDevelopment.ClinicalTrialsOrganisation;
import Business.WorkQueue.LabTestWorkRequest;
import Chemical.Chemical;
import TestingTechnique.InterConnectivity;
import TestingTechnique.IntregatedNetworkTest;
import TestingTechnique.NeighborhoodScoring;
import TestingTechnique.NetworkPropagation;
import TestingTechnique.RandomWalk;
import TestingTechnique.TestingTechnique;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author raunak
 */
public class ProcessWorkRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    LabTestWorkRequest lwr;
    private ClinicalTrialsOrganisation clinicalTrialOrganization;
    /**
     * Creates new form ProcessWorkRequestJPanel
     */
    public ProcessWorkRequestJPanel(JPanel userProcessContainer, LabTestWorkRequest request,ClinicalTrialsOrganisation clinicalTrialOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.lwr = request;
        this.clinicalTrialOrganization = clinicalTrialOrganization;
        testIDjTextField.setText(String.valueOf(lwr.getTestID()));
        drugIDjTextField.setText(String.valueOf(lwr.getTestdrug().getDrugID()));
    
        for(Chemical chemical : lwr.getTestdrug().getTcd().getChemical()){
            chemicaljComboBox.addItem(chemical); 
        }
        
        
        receiverjTextField.setText(String.valueOf(lwr.getReceiver()));
        
        activityjTextField.setText(lwr.getTestdrug().getAcitivity());
        requestdatejTextField.setText(String.valueOf(lwr.getRequestDate()));
        statusjTextField.setText(lwr.getStatus());
        
     
        dgejTextField.setText(lwr.getDge());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        submitJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        testIDjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        drugIDjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chemicaljComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        scorejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        receiverjTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        statusjTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        absorbilityjTextField = new javax.swing.JTextField();
        activityjTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        requestdatejTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        molecularWeightjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        formulajTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        chemicalNamejTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentjTextArea = new javax.swing.JTextArea();
        addUpdatejButton = new javax.swing.JButton();
        startTestjButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        scorejTable = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        dgejTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        aucjTextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        populateScorejButton = new javax.swing.JButton();
        failjRadioButton = new javax.swing.JRadioButton();
        passjRadioButton = new javax.swing.JRadioButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jDateChooser = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(153, 153, 153));

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Result");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Test ID");

        testIDjTextField.setEnabled(false);
        testIDjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testIDjTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Drug ID");

        drugIDjTextField.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Drug Contents");

        chemicaljComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemicaljComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Score");

        scorejTextField.setEnabled(false);
        scorejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scorejTextFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Receiver");

        receiverjTextField.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Status");

        statusjTextField.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Abosorbility");

        absorbilityjTextField.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Acitivity");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Request Date");

        requestdatejTextField.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Resolve Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Chemical Molecular Weight");

        molecularWeightjTextField.setEnabled(false);
        molecularWeightjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                molecularWeightjTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Chemical Formula");

        formulajTextField.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Chemical Name");

        chemicalNamejTextField.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Comment");

        commentjTextArea.setColumns(20);
        commentjTextArea.setRows(5);
        jScrollPane1.setViewportView(commentjTextArea);

        addUpdatejButton.setText("Add/Update");
        addUpdatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUpdatejButtonActionPerformed(evt);
            }
        });

        startTestjButton.setText("Start Test");
        startTestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTestjButtonActionPerformed(evt);
            }
        });

        scorejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network Propagation", "Random Walk", "InterConnectivity", "Neighbordhood Scoring"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(scorejTable);

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("DGE Set ");

        dgejTextField.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("AUC");

        aucjTextField.setEnabled(false);

        jPanel1.setForeground(new java.awt.Color(204, 255, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        populateScorejButton.setText("Populate Score");
        populateScorejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populateScorejButtonActionPerformed(evt);
            }
        });

        failjRadioButton.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(failjRadioButton);
        failjRadioButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        failjRadioButton.setText("Fail");

        passjRadioButton.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(passjRadioButton);
        passjRadioButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        passjRadioButton.setText("Pass");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(statusjTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chemicaljComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(drugIDjTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(receiverjTextField)
                                    .addComponent(testIDjTextField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(requestdatejTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(dgejTextField))))
                            .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(131, 131, 131))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(populateScorejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submitJButton)
                            .addComponent(startTestjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(scorejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(26, 26, 26)
                                .addComponent(absorbilityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(aucjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(27, 27, 27)
                                .addComponent(passjRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(failjRadioButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(activityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(257, 257, 257)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addUpdatejButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chemicalNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(molecularWeightjTextField)
                                    .addComponent(formulajTextField))))
                        .addGap(195, 195, 195))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(formulajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(molecularWeightjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGap(127, 127, 127)
                        .addComponent(startTestjButton)
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(populateScorejButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(testIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10)
                                    .addComponent(chemicalNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(drugIDjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(chemicaljComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(receiverjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(statusjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel32)
                                    .addComponent(dgejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(requestdatejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backJButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(submitJButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addUpdatejButton))
                                        .addGap(53, 53, 53)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(scorejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(absorbilityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel16)
                                            .addComponent(aucjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(activityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(failjRadioButton)
                                            .addComponent(passjRadioButton))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ClinicalTrailResearchWorkAreaJPanel dwjp = (ClinicalTrailResearchWorkAreaJPanel) component;
        dwjp.populateTable(clinicalTrialOrganization);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
        try{Date resolutionDate = jDateChooser.getCalendar().getTime();
        Calendar currentDate = Calendar.getInstance();
        if((resolutionDate == null) || resolutionDate.compareTo(lwr.getRequestDate()) < 0){
            
            jDateChooser.setBackground(Color.red);
            JOptionPane.showMessageDialog(null," Invalid Date");
            jDateChooser.setBackground(Color.white);
          
        }  
        
        else{
        lwr.setResolveDate(jDateChooser.getDate());
        
        if (passjRadioButton.isSelected())
        {
            lwr.setTestResult("Pass");
        }
        else
            lwr.setTestResult("Failed");
        
        
        lwr.getTestdrug().setAcitivity(activityjTextField.getText());
        lwr.getTestdrug().setAreaunderCurve(Double.valueOf(aucjTextField.getText()));
        lwr.getTestdrug().setAbsorbility(Double.valueOf(absorbilityjTextField.getText()));
        lwr.setScore(Double.valueOf(scorejTextField.getText()));
        lwr.setStatus("Completed");
        
        JOptionPane.showMessageDialog(null,"Test Request Completed and Sent ");
        }
        }
        catch(Exception e ){JOptionPane.showMessageDialog(null, "Please enter all Result Fields  ");}
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void testIDjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testIDjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testIDjTextFieldActionPerformed

    private void chemicaljComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemicaljComboBoxActionPerformed
        // TODO add your handling code here:

        Chemical c = (Chemical)chemicaljComboBox.getSelectedItem();

        if(c != null)
        {
            molecularWeightjTextField.setText(String.valueOf(c.getMolecularWeight()));
            formulajTextField.setText(c.getFormula());
            chemicalNamejTextField.setText(c.getChemicalName());
            commentjTextArea.setText(c.getComment());

        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Select a chemical to view detail");
        }

    }//GEN-LAST:event_chemicaljComboBoxActionPerformed

    private void scorejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scorejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scorejTextFieldActionPerformed

    private void molecularWeightjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_molecularWeightjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_molecularWeightjTextFieldActionPerformed

    private void addUpdatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUpdatejButtonActionPerformed
        // TODO add your handling code here:      
        Chemical chemical = (Chemical)chemicaljComboBox.getSelectedItem();
        chemical.setComment(commentjTextArea.getText());
    }//GEN-LAST:event_addUpdatejButtonActionPerformed

    private void startTestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTestjButtonActionPerformed
        // TODO add your handling code here:
        IntregatedNetworkTest test = new IntregatedNetworkTest();
        

       // test.getIc().;
        test.getIc().calculateTestresult();
        test.getNp().calculateTestresult();
        test.getNs().calculateTestresult();
        test.getRw().calculateTestresult();
        
        populateTable(test);
        clinicalTrialOrganization.getNetworkTest();
        
        
        DefaultCategoryDataset barChartData = new DefaultCategoryDataset();
        barChartData.setValue(test.getIc().getScore(), "Score","Interconnectivity");
        barChartData.setValue(test.getIc().getAuc(),"AUC","Interconnectivity");
        barChartData.setValue(test.getIc().getAbsorbility(), "Absorbility","Interconnectivity");
        barChartData.setValue(test.getNp().getScore(), "Score","NetWork Propagation");
        barChartData.setValue(test.getNp().getAuc(),"AUC","NetWork Propagation");
        barChartData.setValue(test.getNp().getAbsorbility(), "Absorbility","NetWork Propagation");
        barChartData.setValue(test.getRw().getScore(), "Score","NeighbourHood Scoring");
        barChartData.setValue(test.getRw().getAuc(),"AUC","NeighbourHood Scoring");
        barChartData.setValue(test.getRw().getAbsorbility(), "Absorbility","NeighbourHood Scoring");
        barChartData.setValue(test.getNs().getScore(), "Score","RandomWalk");
        barChartData.setValue(test.getNs().getAuc(),"AUC","RandomWalk");
        barChartData.setValue(test.getNs().getAbsorbility(), "Absorbility","RandomWalk");
        
        JFreeChart barChart  = ChartFactory.createBarChart
        ("Comparision between all Methods ", "Percentage", "Method Name ", barChartData, PlotOrientation.VERTICAL, false, true, true);
        
        CategoryPlot barbar = barChart.getCategoryPlot();
        barbar.setRangeMinorGridlinePaint(Color.ORANGE);
        
        ChartFrame frame = new  ChartFrame("Bar Chart",barChart);
        frame.setVisible(true);
        frame.setSize(1000, 900);
        frame.pack();
        frame.setLocationRelativeTo(null);
        ChartPanel barPanel = new ChartPanel(barChart);
        
        jPanel1.removeAll();
        jPanel1.add(barPanel);

    }//GEN-LAST:event_startTestjButtonActionPerformed

    private void populateScorejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populateScorejButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedColumn = scorejTable.getSelectedColumn();

        DecimalFormat df = new DecimalFormat("#.##");
        df.setRoundingMode(RoundingMode.CEILING);
        
        
        
        
        if (selectedColumn >= 0) {
            TestingTechnique testingmethod = (TestingTechnique) scorejTable.getValueAt(0,selectedColumn);
            ;
            scorejTextField.setText(String.valueOf(df.format(testingmethod.getScore())));
            absorbilityjTextField.setText(String.valueOf(df.format(testingmethod.getAbsorbility())));
            aucjTextField.setText(String.valueOf(df.format(testingmethod.getAuc())));
        } else {
            JOptionPane.showMessageDialog(null, "Please Select a Method to populate Score !");
        }
        

        
    }//GEN-LAST:event_populateScorejButtonActionPerformed

    public void populateTable(IntregatedNetworkTest test) {
        DefaultTableModel model = (DefaultTableModel) scorejTable.getModel();

        model.setRowCount(0);

         
            Object[] row = new Object[4];
            row[0] = (NetworkPropagation) test.getNp();
            row[1] = (RandomWalk)test.getRw();
            row[2] = (InterConnectivity) test.getIc();
            row[3] = (NeighborhoodScoring) test.getNs();

            model.addRow(row);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absorbilityjTextField;
    private javax.swing.JTextField activityjTextField;
    private javax.swing.JButton addUpdatejButton;
    private javax.swing.JTextField aucjTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField chemicalNamejTextField;
    private javax.swing.JComboBox chemicaljComboBox;
    private javax.swing.JTextArea commentjTextArea;
    private javax.swing.JTextField dgejTextField;
    private javax.swing.JTextField drugIDjTextField;
    private javax.swing.JRadioButton failjRadioButton;
    private javax.swing.JTextField formulajTextField;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField molecularWeightjTextField;
    private javax.swing.JRadioButton passjRadioButton;
    private javax.swing.JButton populateScorejButton;
    private javax.swing.JTextField receiverjTextField;
    private javax.swing.JTextField requestdatejTextField;
    private javax.swing.JTable scorejTable;
    private javax.swing.JTextField scorejTextField;
    private javax.swing.JButton startTestjButton;
    private javax.swing.JTextField statusjTextField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTextField testIDjTextField;
    // End of variables declaration//GEN-END:variables
}
