/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugDiscoveryScientistDDRole;

import Business.Enterprise.Enterprise;
import Business.Organization.ResearchAndDevelopment.DrugDiscoveryOrganisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  
 */
public class DrugDiscoveryScientistWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DrugDiscoveryOrganisation organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DrugDiscoveryScientistWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DrugDiscoveryOrganisation organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        organisationjLabel.setText(organization.getName());
        populateRequestTable();
    }


    
    public void populateRequestTable(){
//       // DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
//        
//        model.setRowCount(0);
//        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
//            Object[] row = new Object[4];
//            row[0] = request.getMessage();
//            row[1] = request.getReceiver();
//            row[2] = request.getStatus();
//            String result = ((LabTestWorkRequest) request).getTestResult();
//            row[3] = result == null ? "Waiting" : result;
//            
//            model.addRow(row);
//        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refreshTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        organisationjLabel = new javax.swing.JLabel();
        logoutjButton = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        drugScientistLeftjPanel = new javax.swing.JPanel();
        preClinicaljButton = new javax.swing.JButton();
        discoverjButton = new javax.swing.JButton();
        clinicalResearchjButton = new javax.swing.JButton();
        drugScientistRightjPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 153, 153));

        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        enterpriseLabel.setText("Enterprise ");

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valueLabel.setText("<value>");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Organisation");

        organisationjLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        organisationjLabel.setText("Org Name");

        logoutjButton.setText("Logout");
        logoutjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutjButtonActionPerformed(evt);
            }
        });

        jSplitPane1.setBackground(new java.awt.Color(255, 255, 0));
        jSplitPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        jSplitPane1.setDividerLocation(300);
        jSplitPane1.setDividerSize(1);

        drugScientistLeftjPanel.setBackground(new java.awt.Color(153, 153, 153));

        preClinicaljButton.setText("Pre-Clinical Trials");
        preClinicaljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preClinicaljButtonActionPerformed(evt);
            }
        });

        discoverjButton.setText("Discovery & Development");
        discoverjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discoverjButtonActionPerformed(evt);
            }
        });

        clinicalResearchjButton.setText("Clinical Research");
        clinicalResearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clinicalResearchjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drugScientistLeftjPanelLayout = new javax.swing.GroupLayout(drugScientistLeftjPanel);
        drugScientistLeftjPanel.setLayout(drugScientistLeftjPanelLayout);
        drugScientistLeftjPanelLayout.setHorizontalGroup(
            drugScientistLeftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugScientistLeftjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(drugScientistLeftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(discoverjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(preClinicaljButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clinicalResearchjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        drugScientistLeftjPanelLayout.setVerticalGroup(
            drugScientistLeftjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drugScientistLeftjPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(discoverjButton)
                .addGap(42, 42, 42)
                .addComponent(preClinicaljButton)
                .addGap(34, 34, 34)
                .addComponent(clinicalResearchjButton)
                .addContainerGap(519, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(drugScientistLeftjPanel);

        drugScientistRightjPanel.setBackground(new java.awt.Color(153, 153, 153));
        drugScientistRightjPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(drugScientistRightjPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(organisationjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 823, Short.MAX_VALUE)
                .addComponent(refreshTestJButton)
                .addGap(30, 30, 30)
                .addComponent(logoutjButton)
                .addGap(61, 61, 61))
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1616, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshTestJButton)
                    .addComponent(logoutjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(organisationjLabel))
                .addGap(45, 45, 45)
                .addComponent(jSplitPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();
        
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void logoutjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        //        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_logoutjButtonActionPerformed

    private void preClinicaljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preClinicaljButtonActionPerformed
        // TODO add your handling code here:
        
        CardLayout layout = (CardLayout) drugScientistRightjPanel.getLayout();
        drugScientistRightjPanel.add("PreClinicalWorkAreaJPanel", new PreClinicalWorkAreaDDJPanel(drugScientistRightjPanel,organization,userAccount,enterprise));
        layout.next(drugScientistRightjPanel);
        
        
        
        
    }//GEN-LAST:event_preClinicaljButtonActionPerformed

    private void discoverjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discoverjButtonActionPerformed
        // TODO add your handling code here:   
        CardLayout layout = (CardLayout) drugScientistRightjPanel.getLayout();
        drugScientistRightjPanel.add("drugScientistRightjPanel", new DiscoveryDevelopmentJPanel(drugScientistRightjPanel,organization,userAccount,enterprise));
        layout.next(drugScientistRightjPanel);

    }//GEN-LAST:event_discoverjButtonActionPerformed

    private void clinicalResearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clinicalResearchjButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Coming Soon ... Work on Progress!");
    }//GEN-LAST:event_clinicalResearchjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clinicalResearchjButton;
    private javax.swing.JButton discoverjButton;
    private javax.swing.JPanel drugScientistLeftjPanel;
    private javax.swing.JPanel drugScientistRightjPanel;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutjButton;
    private javax.swing.JLabel organisationjLabel;
    private javax.swing.JButton preClinicaljButton;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
