/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugDiscoveryScientistDDRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ResearchAndDevelopment.ClinicalTrialsOrganisation;
import Business.Organization.ResearchAndDevelopment.DrugDiscoveryOrganisation;
import Business.WorkQueue.PriclinicalWorkRequest;
import Business.WorkQueue.TiterTest;
import Business.WorkQueue.WorkRequest;
import Chemical.Chemical;
import Drug.NewDiscoveredDrug;
import com.sun.glass.events.KeyEvent;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class InVitroTestRequestDDJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InVitroTestRequestDDJPanel
     */
    private JPanel userprocesscontainer;
    private DrugDiscoveryOrganisation drugDiscoveryOrganisation;
    private NewDiscoveredDrug newDrug;
    private PriclinicalWorkRequest priClinicalwr;
    private Enterprise enterprise;
    private int i = 0;
    private int y = 1;

    public InVitroTestRequestDDJPanel(JPanel userprocesscontainer, NewDiscoveredDrug newDrug, Organization organization, PriclinicalWorkRequest priClinicalwr, Enterprise enterprise) {
        initComponents();
        this.userprocesscontainer = userprocesscontainer;
        this.newDrug = newDrug;
        this.enterprise = enterprise;
        this.drugDiscoveryOrganisation = (DrugDiscoveryOrganisation) organization;
        this.priClinicalwr = priClinicalwr;
        drugjTextField.setText(newDrug.getDrugName());
        populateTable(newDrug);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drugjTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chemicaljTable = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        mediumQuantityjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        doseLeveljTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        expermentTimejSpinner = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        temperaturejSlider = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        titerSetupjTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        assayjSpinner = new javax.swing.JSpinner();
        incubateTempjLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        addPlatesjButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        totalsetjSpinner = new javax.swing.JSpinner();
        addSetupjButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        exposurejTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        wavelengthjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lysistimejSlider = new javax.swing.JSlider();
        timejLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        priorityjSlider = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        requestTestjButton = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));

        drugjTextField.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Drug Name");

        chemicaljTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Chemical ID", "Chemical Name", "Molecular Formula", "Molecular Mass"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(chemicaljTable);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Medium Quantity(µl) ");

        mediumQuantityjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mediumQuantityjTextFieldKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Dose Level(µMolar)");

        doseLeveljTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                doseLeveljTextFieldKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Experiment Time (Min)");

        expermentTimejSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 5));
        expermentTimejSpinner.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Incubate Temperature ");

        temperaturejSlider.setBackground(new java.awt.Color(153, 153, 153));
        temperaturejSlider.setMinimum(-50);
        temperaturejSlider.setMinorTickSpacing(5);
        temperaturejSlider.setPaintTicks(true);
        temperaturejSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                temperaturejSliderMouseMoved(evt);
            }
        });

        titerSetupjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titer Plate No", "Total Assay ", "Dose Level"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(titerSetupjTable);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Number of Assay");

        assayjSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 96, 12));

        incubateTempjLabel.setText("30 ");

        jLabel16.setText("°C");

        jLabel17.setText("-50°C");

        jLabel19.setText("100°C");

        addPlatesjButton.setText("Add Total Plates");
        addPlatesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlatesjButtonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Set Total Number of MicroTitter Plate");

        totalsetjSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        addSetupjButton1.setText("Add Setup");
        addSetupjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSetupjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(28, 28, 28)
                                    .addComponent(totalsetjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(36, 36, 36))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(assayjSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(mediumQuantityjTextField)
                                        .addComponent(doseLeveljTextField))))
                            .addGap(56, 56, 56)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addPlatesjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addSetupjButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(35, 35, 35)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addGap(82, 82, 82)
                            .addComponent(incubateTempjLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel16)
                            .addGap(62, 62, 62)
                            .addComponent(jLabel19)
                            .addGap(512, 512, 512)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(expermentTimejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(temperaturejSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalsetjSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addPlatesjButton)
                                .addComponent(jLabel15)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(assayjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mediumQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doseLeveljTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(addSetupjButton1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(expermentTimejSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(temperaturejSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(incubateTempjLabel)
                                .addComponent(jLabel16))
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136))
        );

        jTabbedPane1.addTab("Experiment MainSetup ", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Exposure (sec)");
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 25));

        exposurejTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                exposurejTextFieldKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Detection WaveLength(nm) ");
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 25));

        wavelengthjTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                wavelengthjTextFieldKeyPressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Cell Lysis Time (Min)");
        jLabel9.setPreferredSize(new java.awt.Dimension(200, 25));

        lysistimejSlider.setBackground(new java.awt.Color(153, 153, 153));
        lysistimejSlider.setMaximum(10);
        lysistimejSlider.setMinorTickSpacing(1);
        lysistimejSlider.setPaintTicks(true);
        lysistimejSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lysistimejSliderMouseMoved(evt);
            }
        });

        timejLabel.setText("10");

        jLabel14.setText("minutes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lysistimejSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(exposurejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(wavelengthjTextField))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(timejLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exposurejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wavelengthjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lysistimejSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timejLabel)
                    .addComponent(jLabel14))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Luminescent Cell Viability Set up ", jPanel2);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Dye ");

        priorityjSlider.setBackground(new java.awt.Color(153, 153, 153));
        priorityjSlider.setMaximum(3);
        priorityjSlider.setMinimum(1);
        priorityjSlider.setMinorTickSpacing(1);
        priorityjSlider.setPaintTicks(true);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Priority");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Estimated Day of Delivery ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Formazen", "BioMarker", "RadioActiveMarker", "Fluroscent Activated Marker" }));
        jComboBox1.setToolTipText("");

        jLabel2.setText("Low");

        jLabel18.setText("Medium");

        jLabel20.setText("High");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                    .addComponent(jLabel12))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(priorityjSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel20)))
                .addContainerGap(640, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priorityjSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Other Set up ", jPanel3);

        requestTestjButton.setText("Request Test ");
        requestTestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestjButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(requestTestjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(drugjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(drugjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestTestjButton)
                    .addComponent(jButton1))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestjButtonActionPerformed
        // TODO add your handling code here:

//        if (JOptionPane.showConfirmDialog(null, "please Confirm?", "Information",
//        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        try {
            String EMPTY = "";
            if (exposurejTextField == null || wavelengthjTextField == null || exposurejTextField.getText().equals(EMPTY) || wavelengthjTextField.getText().equals(EMPTY)) {
                JOptionPane.showMessageDialog(null, " Please Enter all the experiment setup details ");
            } 
            else {

                // yes option
                priClinicalwr.setTotalSetTitter(Integer.parseInt(String.valueOf(totalsetjSpinner.getValue())));
                priClinicalwr.setExperimentTime(Integer.parseInt(String.valueOf(expermentTimejSpinner.getValue())));
                priClinicalwr.setTemperature(Integer.parseInt(String.valueOf(temperaturejSlider.getValue())));
                priClinicalwr.setExposure(Integer.valueOf(exposurejTextField.getText()));
                priClinicalwr.setWavelength(Integer.valueOf(wavelengthjTextField.getText()));
                priClinicalwr.setLysistime(Integer.parseInt(String.valueOf(lysistimejSlider.getValue())));
                priClinicalwr.setPriority(String.valueOf(priorityjSlider.getValue()));
                Calendar choosenDate = jDateChooser.getCalendar();
                Calendar currentDate = Calendar.getInstance();
                if ((choosenDate == null) || choosenDate.compareTo(currentDate) < 0) {

                    jDateChooser.setBackground(Color.red);
                    JOptionPane.showMessageDialog(null, " Invalid Date");
                    jDateChooser.setBackground(Color.white);

                    
                }
                else{

                priClinicalwr.setEstimatedDayofDelivery(jDateChooser.getDate());
                priClinicalwr.setDrugID(newDrug.getDrugID());
                //  System.out.println("DrugNmae in PriClinical " + newDrug.getDrugName());
                priClinicalwr.setDrugName(newDrug.getDrugName());
                //  priClinicalwr.setStatus("Sent");
                priClinicalwr.setDiseaseName(newDrug.getDiseasename());

                Organization org = null;
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof ClinicalTrialsOrganisation) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {
                    ClinicalTrialsOrganisation cto = (ClinicalTrialsOrganisation) org;

                    cto.getPriclinicalWorkQueue().getWorkRequestList().add(priClinicalwr);
                    // userAccount.getWorkQueue().getWorkRequestList().add(request);
                }
                JOptionPane.showMessageDialog(null, "Experiment  Requested ");
                }

                
            }
        } catch (Exception e) {
            System.out.println(" Input invalid ");
            JOptionPane.showMessageDialog(null, " Please Enter all the experiment setup details ");
        }

    }//GEN-LAST:event_requestTestjButtonActionPerformed

    private void lysistimejSliderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lysistimejSliderMouseMoved
        // TODO add your handling code here:
        timejLabel.setText(String.valueOf(lysistimejSlider.getValue()));

    }//GEN-LAST:event_lysistimejSliderMouseMoved

    private void temperaturejSliderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_temperaturejSliderMouseMoved
        // TODO add your handling code here:
        incubateTempjLabel.setText(String.valueOf(temperaturejSlider.getValue()));

    }//GEN-LAST:event_temperaturejSliderMouseMoved

    private void addPlatesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlatesjButtonActionPerformed
        // TODO add your handling code here:
        this.i = Integer.parseInt(String.valueOf(totalsetjSpinner.getValue()));
        JOptionPane.showMessageDialog(null, "Total " + this.i + " of Plates added");

    }//GEN-LAST:event_addPlatesjButtonActionPerformed

    private void addSetupjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSetupjButton1ActionPerformed
        // TODO add your handling code here:

        if (y <= i) {

            TiterTest titertest = new TiterTest();
            titertest.setMediumQuantity(Double.parseDouble(mediumQuantityjTextField.getText()));
            titertest.setTotalNumberofAssay(Integer.parseInt(String.valueOf(assayjSpinner.getValue())));
            priClinicalwr.getTiterPlate().add(titertest);

            populateTiterTable();
            y++;

        } else {
            JOptionPane.showMessageDialog(null, "Please add Total Number of MicrotiterPlate");

        }


    }//GEN-LAST:event_addSetupjButton1ActionPerformed

    private void mediumQuantityjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mediumQuantityjTextFieldKeyPressed
        // TODO add your handling code here:
        int keyp = evt.getKeyCode();
        if (keyp == 46) {
            keyp = 110;
        }
        if ((keyp == KeyEvent.VK_BACKSPACE) || (keyp >= evt.VK_0 && keyp <= evt.VK_9 || (keyp == evt.VK_DECIMAL))) {
            mediumQuantityjTextField.setEditable(true);
            mediumQuantityjTextField.setBackground(Color.YELLOW);

        } else {
            mediumQuantityjTextField.setEditable(false);
            mediumQuantityjTextField.setBackground(Color.red);
            // getToolkit().beep();
            JOptionPane.showMessageDialog(null, " Characters Prohibited ");
            mediumQuantityjTextField.setBackground(Color.WHITE);
            // userNamejTextField.requestFocusInWindow();
        }
    }//GEN-LAST:event_mediumQuantityjTextFieldKeyPressed

    private void doseLeveljTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_doseLeveljTextFieldKeyPressed
        // TODO add your handling code here:
        int keyp = evt.getKeyCode();
        if (keyp == 46) {
            keyp = 110;
        }
        if ((keyp == KeyEvent.VK_BACKSPACE) || (keyp >= evt.VK_0 && keyp <= evt.VK_9) || (keyp == evt.VK_DECIMAL)) {
            doseLeveljTextField.setEditable(true);
            doseLeveljTextField.setBackground(Color.YELLOW);

        } else {
            doseLeveljTextField.setEditable(false);
            doseLeveljTextField.setBackground(Color.red);
            // getToolkit().beep();
            JOptionPane.showMessageDialog(null, " Characters Prohibited ");
            doseLeveljTextField.setBackground(Color.WHITE);
            // userNamejTextField.requestFocusInWindow();
        }
    }//GEN-LAST:event_doseLeveljTextFieldKeyPressed

    private void exposurejTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exposurejTextFieldKeyPressed
        // TODO add your handling code here:
        int keyp = evt.getKeyCode();
        if (keyp == 46) {
            keyp = 110;
        }
        if ((keyp == KeyEvent.VK_BACKSPACE) || (keyp >= evt.VK_0 && keyp <= evt.VK_9) || (keyp == evt.VK_DECIMAL)) {
            exposurejTextField.setEditable(true);
            exposurejTextField.setBackground(Color.YELLOW);

        } else {
            exposurejTextField.setEditable(false);
            exposurejTextField.setBackground(Color.red);
            // getToolkit().beep();
            JOptionPane.showMessageDialog(null, " Characters Prohibited ");
            exposurejTextField.setBackground(Color.WHITE);
            // userNamejTextField.requestFocusInWindow();
        }


    }//GEN-LAST:event_exposurejTextFieldKeyPressed

    private void wavelengthjTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_wavelengthjTextFieldKeyPressed
        // TODO add your handling code here:
        int keyp = evt.getKeyCode();
        if (keyp == 46) {
            keyp = 110;
        }
        if ((keyp == KeyEvent.VK_BACKSPACE) || (keyp >= evt.VK_0 && keyp <= evt.VK_9) || (keyp == evt.VK_DECIMAL)) {
            wavelengthjTextField.setEditable(true);
            wavelengthjTextField.setBackground(Color.YELLOW);

        } else {
            wavelengthjTextField.setEditable(false);
            wavelengthjTextField.setBackground(Color.red);
            // getToolkit().beep();
            JOptionPane.showMessageDialog(null, " Characters Prohibited ");
            wavelengthjTextField.setBackground(Color.WHITE);
            // userNamejTextField.requestFocusInWindow();
        }
    }//GEN-LAST:event_wavelengthjTextFieldKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        userprocesscontainer.remove(this);
        Component[] componentArray = userprocesscontainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
//        DrugDiscoveryScientistWorkAreaJPanel dwjp = (DrugDiscoveryScientistWorkAreaJPanel) component;
//        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
        layout.previous(userprocesscontainer);


    }//GEN-LAST:event_jButton1ActionPerformed

    public void populateTiterTable() {

        DefaultTableModel model = (DefaultTableModel) titerSetupjTable.getModel();

        model.setRowCount(0);

        for (TiterTest titer : priClinicalwr.getTiterPlate()) {
            Object[] row = new Object[3];

            row[0] = titer;
            row[1] = titer.getMediumQuantity();
            row[2] = titer.getTotalNumberofAssay();
            model.addRow(row);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlatesjButton;
    private javax.swing.JButton addSetupjButton1;
    private javax.swing.JSpinner assayjSpinner;
    private javax.swing.JTable chemicaljTable;
    private javax.swing.JTextField doseLeveljTextField;
    private javax.swing.JTextField drugjTextField;
    private javax.swing.JSpinner expermentTimejSpinner;
    private javax.swing.JTextField exposurejTextField;
    private javax.swing.JLabel incubateTempjLabel;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSlider lysistimejSlider;
    private javax.swing.JTextField mediumQuantityjTextField;
    private javax.swing.JSlider priorityjSlider;
    private javax.swing.JButton requestTestjButton;
    private javax.swing.JSlider temperaturejSlider;
    private javax.swing.JLabel timejLabel;
    private javax.swing.JTable titerSetupjTable;
    private javax.swing.JSpinner totalsetjSpinner;
    private javax.swing.JTextField wavelengthjTextField;
    // End of variables declaration//GEN-END:variables

    private void populateTable(NewDiscoveredDrug newDrug) {

        DefaultTableModel model = (DefaultTableModel) chemicaljTable.getModel();

        model.setRowCount(0);
        ///System.out.println("Size is " + newDrug.getTcd().getChemical().size());

        for (Chemical chemical : newDrug.getTcd().getChemical()) {

            Object[] row = new Object[7];
            row[0] = chemical.getChemicalID();
            row[1] = chemical.getChemicalName();
            row[2] = chemical.getFormula();
            row[3] = chemical.getMolecularWeight();

            model.addRow(row);

        }

    }
}
