/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugDiscoveryScientistDDRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ResearchAndDevelopment.DrugDiscoveryOrganisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author Lenovo
 */
public class PreClinicalWorkAreaDDJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PreClinicalWorkAreaDDJPanel
     */
     private  JPanel userprocesscontainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private DrugDiscoveryOrganisation organization;
   
    
    
    

    public PreClinicalWorkAreaDDJPanel(JPanel drugScientistRightjPanel, DrugDiscoveryOrganisation organization, UserAccount userAccount, Enterprise enterprise) {
        
        initComponents();
        this.userprocesscontainer = drugScientistRightjPanel;
        this.organization = organization;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageNewDrugjButton = new javax.swing.JButton();
        manageResearchjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));

        manageNewDrugjButton.setText("Manage New  Approved Drug");
        manageNewDrugjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageNewDrugjButtonActionPerformed(evt);
            }
        });

        manageResearchjButton.setText("Manage In-Vitro Research");
        manageResearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageResearchjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(489, 489, 489)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageNewDrugjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageResearchjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(612, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(manageNewDrugjButton)
                .addGap(62, 62, 62)
                .addComponent(manageResearchjButton)
                .addContainerGap(394, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageNewDrugjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageNewDrugjButtonActionPerformed
        // TODO add your handling code here:
          
            CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
            userprocesscontainer.add("PreClinicalJPanel", new InitiatePreClinicalResearchDDJPanel(userprocesscontainer,organization,userAccount,enterprise));
            layout.next(userprocesscontainer);
        
        
        
    }//GEN-LAST:event_manageNewDrugjButtonActionPerformed

    private void manageResearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageResearchjButtonActionPerformed
        // TODO add your handling code here:
        
        
            CardLayout layout = (CardLayout) userprocesscontainer.getLayout();
            userprocesscontainer.add("InVitoResearchResultDDJPanel", new InVitoResearchResultDDJPanel(userprocesscontainer,organization,userAccount,enterprise));
            layout.next(userprocesscontainer);
    }//GEN-LAST:event_manageResearchjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageNewDrugjButton;
    private javax.swing.JButton manageResearchjButton;
    // End of variables declaration//GEN-END:variables
}
