/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugDiscoveryScientistDDRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ResearchAndDevelopment.ClinicalTrialsOrganisation;
import Business.Organization.ResearchAndDevelopment.DrugDiscoveryOrganisation;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import Chemical.Chemical;
import Chemical.TestChemicalDirectory;
import Disease.Disease;
import Drug.AvailableDrug;
import Drug.TestDrug;
import com.sun.glass.events.KeyEvent;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class ReasearchNewChemicalDrugJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReasearchNewChemicalDrug
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Organization organization;
    private TestChemicalDirectory tcd;

    public ReasearchNewChemicalDrugJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Organization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.organization = organization;
        populateComboBox();
        tcd = new TestChemicalDirectory();

    }

    private void populateComboBox() {
        diseasejComboBox.removeAllItems();
        DrugDiscoveryOrganisation drugdd = (DrugDiscoveryOrganisation) organization;
        for (Disease disease : drugdd.getDd().getDisease()) {
            diseasejComboBox.addItem(disease);
        }
    }

    private void populateOtherChemicalList() {
        DrugDiscoveryOrganisation drugdd = (DrugDiscoveryOrganisation) organization;
        int selectedRow = drugListjTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) otherChemicaListjTable.getModel();

        model.setRowCount(0);
        for (Disease disease : drugdd.getDd().getDisease()) {
            for (AvailableDrug drug : disease.getAvalaibleDrug()) {
                AvailableDrug availdrug = (AvailableDrug) drugListjTable.getValueAt(selectedRow, 1);
                if (drug.equals(availdrug)) {
                    break;
                }
                //     if (organization instanceof LabOrganization){
                // break;    

                for (Chemical chemical : drug.getChemicalList().getChemical()) {

                    Object[] row = new Object[5];
                    row[0] = chemical.getChemicalID();
                    row[1] = chemical;
                    row[2] = chemical.getMolecularWeight();
                    row[3] = chemical.getFormula();

                    model.addRow(row);
                }
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        diseasejRadioButton = new javax.swing.JRadioButton();
        healthyjRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        addChemicaljButton = new javax.swing.JButton();
        diseasejComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        genejTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chemicalmolWeightJtext = new javax.swing.JTextField();
        requestTestjButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        formulajTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        drugListjTable = new javax.swing.JTable();
        selectedChemicalsjComboBox = new javax.swing.JComboBox();
        removejButton = new javax.swing.JButton();
        resetjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        otherChemicaListjTable = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        chemicalListjTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        chemicalListjButton = new javax.swing.JButton();
        addChemicalOtherjButton = new javax.swing.JButton();
        AddjButton = new javax.swing.JButton();
        chemicalNamejTextField = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        chemicalCommentjTextArea = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Select Gene Property");

        diseasejRadioButton.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(diseasejRadioButton);
        diseasejRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        diseasejRadioButton.setText("Disease");

        healthyjRadioButton.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroup1.add(healthyjRadioButton);
        healthyjRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        healthyjRadioButton.setText("Healthy");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Chemical Compund Name");

        addChemicaljButton.setText("Show Details ");
        addChemicaljButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChemicaljButtonActionPerformed(evt);
            }
        });

        diseasejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseasejComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Disease");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Disease Target  Gene");

        genejTextArea.setColumns(20);
        genejTextArea.setRows(5);
        genejTextArea.setEnabled(false);
        jScrollPane3.setViewportView(genejTextArea);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Selected Chemical Compounds");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Chemical Molecular Weight");

        chemicalmolWeightJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemicalmolWeightJtextActionPerformed(evt);
            }
        });
        chemicalmolWeightJtext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                chemicalmolWeightJtextKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chemicalmolWeightJtextKeyTyped(evt);
            }
        });

        requestTestjButton.setText("Request Test");
        requestTestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestjButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Chemical Formula");

        formulajTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formulajTextFieldKeyPressed(evt);
            }
        });

        drugListjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "ActiveDate", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(drugListjTable);

        removejButton.setText("Remove  Chemical ");
        removejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removejButtonActionPerformed(evt);
            }
        });

        resetjButton.setBackground(new java.awt.Color(153, 153, 153));
        resetjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/DrugDiscoveryScientistDDRole/1481472822_free-38.png"))); // NOI18N
        resetjButton.setBorderPainted(false);
        resetjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetjButtonActionPerformed(evt);
            }
        });

        otherChemicaListjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Chemical ID", "Chemical Name", "Molecular Weight", "Formula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(otherChemicaListjTable);

        chemicalListjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Chemical ID", "Chemical Name", "Molecular Weight", "Formula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(chemicalListjTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Drug List");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Other Chemical List");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Chemical List");

        chemicalListjButton.setText("Show Chemical List ");
        chemicalListjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chemicalListjButtonActionPerformed(evt);
            }
        });

        addChemicalOtherjButton.setText("Show Details");
        addChemicalOtherjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChemicalOtherjButtonActionPerformed(evt);
            }
        });

        AddjButton.setText("Add Chemical");
        AddjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddjButtonActionPerformed(evt);
            }
        });

        chemicalCommentjTextArea.setColumns(20);
        chemicalCommentjTextArea.setRows(5);
        jScrollPane5.setViewportView(chemicalCommentjTextArea);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Comments");

        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diseasejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4)
                                    .addComponent(jScrollPane1)
                                    .addComponent(chemicalListjButton, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addChemicaljButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addChemicalOtherjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(diseasejRadioButton)
                                                .addGap(36, 36, 36)
                                                .addComponent(healthyjRadioButton))
                                            .addComponent(formulajTextField)
                                            .addComponent(chemicalmolWeightJtext)
                                            .addComponent(chemicalNamejTextField)
                                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(removejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(selectedChemicalsjComboBox, 0, 199, Short.MAX_VALUE)
                                            .addComponent(AddjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(resetjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(639, 639, 639)
                                .addComponent(requestTestjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diseasejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(6, 6, 6)
                        .addComponent(chemicalListjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(addChemicaljButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addChemicalOtherjButton)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(diseasejRadioButton)
                            .addComponent(healthyjRadioButton))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(chemicalNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(chemicalmolWeightJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(formulajTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(25, 25, 25)
                        .addComponent(AddjButton)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectedChemicalsjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resetjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(removejButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestTestjButton)
                    .addComponent(backjButton))
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void diseasejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseasejComboBoxActionPerformed
        // TODO add your handling code here:
        Disease disease = (Disease) diseasejComboBox.getSelectedItem();
        DefaultTableModel model = (DefaultTableModel) drugListjTable.getModel();

        model.setRowCount(0);

        for (AvailableDrug availdrug : disease.getAvalaibleDrug()) {

            Object[] row = new Object[5];
            row[0] = availdrug.getDrugID();
            row[1] = availdrug;
            row[2] = availdrug.getActiveDate();
            row[3] = availdrug.getStatus();

            model.addRow(row);

        }
        genejTextArea.setText(disease.getGene());


    }//GEN-LAST:event_diseasejComboBoxActionPerformed

    private void chemicalmolWeightJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemicalmolWeightJtextActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_chemicalmolWeightJtextActionPerformed

    private void requestTestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestjButtonActionPerformed
        // TODO add your handling code here:

        if (!(selectedChemicalsjComboBox.getItemCount() == 0)) {

            DrugDiscoveryOrganisation drugdd = (DrugDiscoveryOrganisation) organization;
            WorkQueue wq = drugdd.getWorkQueue();
            LabTestWorkRequest request = new LabTestWorkRequest();
            if (diseasejRadioButton.isSelected()) {
                request.setDge("Disease");
            } else {
                request.setDge("Healthy");
            }

            request.setSender(userAccount);
            request.setStatus("Sent");

            TestDrug td = new TestDrug();
            td.setTcd(tcd);
            td.setDiseasename(String.valueOf(diseasejComboBox.getSelectedItem()));

            request.setTestdrug(td);

            Organization org = null;
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof ClinicalTrialsOrganisation) {
                    org = organization;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            }

            JOptionPane.showMessageDialog(null, "Experiment Requested ");
        } else {
            JOptionPane.showMessageDialog(null, "Please Choose Chemical for the Experiment");
        }


    }//GEN-LAST:event_requestTestjButtonActionPerformed

    private void chemicalListjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chemicalListjButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = drugListjTable.getSelectedRow();

        if (selectedRow >= 0) {
            AvailableDrug availdrug = (AvailableDrug) drugListjTable.getValueAt(selectedRow, 1);

            DefaultTableModel model = (DefaultTableModel) chemicalListjTable.getModel();

            model.setRowCount(0);

            for (Chemical chemical : availdrug.getChemicalList().getChemical()) {

                Object[] row = new Object[5];
                row[0] = chemical.getChemicalID();
                row[1] = chemical;
                row[2] = chemical.getMolecularWeight();
                row[3] = chemical.getFormula();

                model.addRow(row);

                populateOtherChemicalList();

            }

        } else {
            JOptionPane.showMessageDialog(null, "Please Select a Drug to Re-Test");
        }

    }//GEN-LAST:event_chemicalListjButtonActionPerformed

    private void addChemicaljButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChemicaljButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = chemicalListjTable.getSelectedRow();

        if (selectedRow >= 0) {
            Chemical chemical = (Chemical) chemicalListjTable.getValueAt(selectedRow, 1);
            chemicalNamejTextField.setText(chemical.getChemicalName());
            chemicalmolWeightJtext.setText(String.valueOf(chemical.getMolecularWeight()));
            formulajTextField.setText(chemical.getFormula());

        } else {
            JOptionPane.showMessageDialog(null, "Please Select a Chemical to ADD ");
        }

    }//GEN-LAST:event_addChemicaljButtonActionPerformed

    private void addChemicalOtherjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChemicalOtherjButtonActionPerformed
        // TODO add your handling code here:

        int selectedRow = otherChemicaListjTable.getSelectedRow();

        if (selectedRow >= 0) {
            Chemical chemical = (Chemical) otherChemicaListjTable.getValueAt(selectedRow, 1);
            chemicalNamejTextField.setText(chemical.getChemicalName());
            chemicalmolWeightJtext.setText(String.valueOf(chemical.getMolecularWeight()));
            formulajTextField.setText(chemical.getFormula());

        } else {
            JOptionPane.showMessageDialog(null, "Please Select a Chemical to ADD ");
        }


    }//GEN-LAST:event_addChemicalOtherjButtonActionPerformed

    private void AddjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddjButtonActionPerformed

        if ((diseasejRadioButton.isSelected() || healthyjRadioButton.isSelected())) {
            String EMPTY = "";
            if ((chemicalNamejTextField == null || chemicalmolWeightJtext == null) && (chemicalNamejTextField.getText().equals(EMPTY) || chemicalmolWeightJtext == null
                    || formulajTextField == null) || chemicalCommentjTextArea == null || chemicalmolWeightJtext.getText().equals(EMPTY) || formulajTextField.equals(EMPTY) || chemicalCommentjTextArea.equals(EMPTY)) {
                JOptionPane.showMessageDialog(null, "Please Enter all the data related to Chemical ");
            } else {
                tcd.addChemical(chemicalNamejTextField.getText(), Double.parseDouble(chemicalmolWeightJtext.getText()), formulajTextField.getText(), chemicalCommentjTextArea.getText());
                populateComboBoxSelectedChemicals(tcd);
                JOptionPane.showMessageDialog(null, "Test Chemical Added");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please Select the Healthy/UnHealthy Set");
        }

//        chemicalNamejTextField.setText("");
//        chemicalmolWeightJtext.setText("");
//        formulajTextField.setText("");

    }//GEN-LAST:event_AddjButtonActionPerformed

    private void removejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removejButtonActionPerformed
        // TODO add your handling code here:

        Chemical chemical = (Chemical) selectedChemicalsjComboBox.getSelectedItem();

        tcd.removeChemical(chemical);
        selectedChemicalsjComboBox.removeAllItems();
        for (Chemical chemicals : tcd.getChemical()) {
            selectedChemicalsjComboBox.addItem(chemicals);
        }

//        Disease disease = (Disease)diseasejComboBox.getSelectedItem();
//        disease.getTestdrug();
//        Chemical chemical = (Chemical)selectedChemicalsjComboBox.getSelectedItem();    
    }//GEN-LAST:event_removejButtonActionPerformed

    private void resetjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetjButtonActionPerformed
        // TODO add your handling code here:

        buttonGroup1.clearSelection();
        chemicalNamejTextField.setText("");
        chemicalmolWeightJtext.setText("");
        formulajTextField.setText("");
        chemicalCommentjTextArea.setText("");
        selectedChemicalsjComboBox.removeAllItems();


    }//GEN-LAST:event_resetjButtonActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DiscoveryDevelopmentJPanel dwjp = (DiscoveryDevelopmentJPanel) component;
        dwjp.populateTable(organization);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void formulajTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formulajTextFieldKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_formulajTextFieldKeyPressed

    private void chemicalmolWeightJtextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chemicalmolWeightJtextKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_chemicalmolWeightJtextKeyTyped

    private void chemicalmolWeightJtextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chemicalmolWeightJtextKeyPressed
        int keyp = evt.getKeyCode();

        if (keyp == 46) {
            keyp = 110;
        }
        if ((keyp == KeyEvent.VK_BACKSPACE) || (keyp >= evt.VK_0 && keyp <= evt.VK_9) || (keyp == evt.VK_DECIMAL)) {
            chemicalmolWeightJtext.setEditable(true);
            chemicalmolWeightJtext.setBackground(Color.YELLOW);

        } else {
            chemicalmolWeightJtext.setEditable(false);
            chemicalmolWeightJtext.setBackground(Color.red);
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Special Characters Prohibited ");
            chemicalmolWeightJtext.setBackground(Color.WHITE);
            chemicalmolWeightJtext.requestFocusInWindow();
        }
    }//GEN-LAST:event_chemicalmolWeightJtextKeyPressed

    public void populateComboBoxSelectedChemicals(TestChemicalDirectory tcd) {

        selectedChemicalsjComboBox.removeAllItems();
        for (Chemical chemical : tcd.getChemical()) {
            selectedChemicalsjComboBox.addItem(chemical);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddjButton;
    private javax.swing.JButton addChemicalOtherjButton;
    private javax.swing.JButton addChemicaljButton;
    private javax.swing.JButton backjButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea chemicalCommentjTextArea;
    private javax.swing.JButton chemicalListjButton;
    private javax.swing.JTable chemicalListjTable;
    private javax.swing.JTextField chemicalNamejTextField;
    private javax.swing.JTextField chemicalmolWeightJtext;
    private javax.swing.JComboBox diseasejComboBox;
    private javax.swing.JRadioButton diseasejRadioButton;
    private javax.swing.JTable drugListjTable;
    private javax.swing.JTextField formulajTextField;
    private javax.swing.JTextArea genejTextArea;
    private javax.swing.JRadioButton healthyjRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable otherChemicaListjTable;
    private javax.swing.JButton removejButton;
    private javax.swing.JButton requestTestjButton;
    private javax.swing.JButton resetjButton;
    private javax.swing.JComboBox selectedChemicalsjComboBox;
    // End of variables declaration//GEN-END:variables
}
